# Generated by Django 5.2 on 2025-05-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('results', models.JSONField()),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
