# Generated by Django 5.2 on 2025-05-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delay',
            name='user_id',
            field=models.CharField(max_length=128),
        ),
    ]
