# Generated by Django 5.2 on 2025-05-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_delay_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=128)),
            ],
        ),
    ]
